const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';
const SET_ACTIVE_TRUE = 'SET_ACTIVE_TRUE';
const SET_ACTIVE_FALSE = 'SET_ACTIVE_FALSE';
const SET_UPWARD_TRUE = 'SET_UPWARD_TRUE';
const SET_UPWARD_FALSE = 'SET_UPWARD_FALSE';

export {
    SET_SELECTED_OPTION,
    SET_ACTIVE_TRUE,
    SET_ACTIVE_FALSE,
    SET_UPWARD_TRUE,
    SET_UPWARD_FALSE
}
