export const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';
export const SET_ACTIVE_TRUE = 'SET_ACTIVE_TRUE';
export const SET_ACTIVE_FALSE = 'SET_ACTIVE_FALSE';
export const SET_UPWARD_TRUE = 'SET_UPWARD_TRUE';
export const SET_UPWARD_FALSE = 'SET_UPWARD_FALSE';
