const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
const SET_PLACEHOLDER = 'SET_PLACEHOLDER';
const SET_PLACEHOLDER_POSITION = 'SET_PLACEHOLDER_POSITION';

export {
    SET_FILTER_TEXT,
    SET_PLACEHOLDER,
    SET_PLACEHOLDER_POSITION
}
